[template variables]
ns=Suite configuration

[template variables=COMPARE_OUTPUT]
compulsory=true
description=Flag to turn on/off KGO comparisons (NOT USED)
help=If not present and 'TRUE' the suite_report script generates a large
    =warning saying the rose-stem tests are invalid as this variable is used
    =in the UM where the suite_report script is copied from.
type=boolean

[template variables=COMPARE_WALLCLOCK]
compulsory=true
description=Flag to turn on/off wallclock comparisons (NOT USED)
help=If not present and 'TRUE' the suite_report script generates a large
    =warning saying the rose-stem tests are invalid as this variable is used
    =in the UM where the suite_report script is copied from.
type=boolean

[template variables=COVERAGE]
compulsory=true
description=Generate code coverage statistics (Met Office only)
type=boolean

[template variables=FCM_VERSION]
compulsory=true
description=Version of FCM to use for make tasks
           =Leave blank for site default
type=character

[template variables=HOUSEKEEPING]
compulsory=true
description=Delete output from model runs which succeed
type=boolean

[template variables=JASMIN_JULES_BASE_DIR]
compulsory=false
description=Base dir with important libraries and data
help=Set this to be the group workspace for JULES on JASMIN
type=character

[template variables=JASMIN_USER_ID]
compulsory=false
description=Only required for JASMIN. User ID to connect to JASMIN with
type=character

[template variables=REMOTE_JASMIN]
compulsory=true
description=Using a remote connection to JASMIN
type=boolean

[template variables=REMOTE_JULES_SOURCE]
compulsory=false
description=Path to the JULES code on JASMIN
type=character

[template variables=RUN_NAMES]
compulsory=true
description=Tasks to run (see wiki page for more info)
type=python_list

[template variables=SOURCE_JULES]
compulsory=true
description=The JULES source to use
           =If running with rose-stem, this is overridden
type=character

[template variables=SUITE_TIMEOUT]
compulsory=true
description=Suite timeout period
help=The suite will automatically shut down once there have been no activity
    =for this period.
type=character
