[namelist:jules_land_frac]
compulsory=true
description=When the input grid is a single point, that single point is assumed to be 100% land
ns=namelist/Grid configuration/Land fraction
sort-key=13
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#namelist-JULES_LAND_FRAC

[namelist:jules_land_frac=file]
description=File to read land fraction data from
sort-key=1
type=character
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#JULES_LAND_FRAC::file

[namelist:jules_land_frac=l_use_land_fraction]
compulsory=true
description=Use land fractions and pass these to river routing
fail-if=this == '.true.' and ( namelist:jules_rivers=i_river_vn != 3 or namelist:jules_model_environment=lsm_id != 3 ); # Land fractions are only used by TRIP in Rivers-standalone to determine coastal endorheic basins.
sort-key=3
type=logical
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#JULES_LAND_FRAC::l_use_land_fraction

[namelist:jules_land_frac=land_frac_name]
description=Name of the variable containing the land fraction data
sort-key=2
type=character
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#JULES_LAND_FRAC::land_frac_name
