[namelist:imogen_run_list]
!!c_emissions=.false.
ch4_init_ppbv=774.1
ch4_ppbv_ref=1751.02
fch4_ref=180.0
file_ch4_n2o='$IMOGEN_INSTALL_DIR/rose_stem_imogen/example_ch4_n2o_conc.dat'
!!file_scen_emits='$IMOGEN_INSTALL_DIR/ancil/emiss_co2.dat'
include_co2=.false.
!!initial_co2_ch4_year=1860
land_feed_ch4=.true.
!!land_feed_co2=.false.
nyr_ch4_n2o=241
!!nyr_emiss=241
!!ocean_feed=.false.
tau_ch4_ref=8.4
yr_fch4_ref=2000
