[namelist:imogen_run_list]
c_emissions=.false.
change_metdata_method=3
!!file_non_co2_radf='$IMOGEN_INSTALL_DIR/ancil/RF_NONCO2_GHG_IS92A.dat'
file_scen_co2_ppmv='$IMOGEN_INSTALL_DIR/rose_stem_imogen/example_co2_conc.dat'
!!file_scen_emits='$IMOGEN_INSTALL_DIR/ancil/emiss_co2.dat'
include_non_co2_radf=.false.
!!initial_co2_ch4_year=1860
!!land_feed_co2=.false.
!!nyr_emiss=241
!!nyr_non_co2=241
!!ocean_feed=.false.

[namelist:jules_prescribed]
n_datasets=1

[namelist:jules_prescribed_dataset(1)]
data_end='2100-01-01 00:00:00'
data_period=-2
data_start='1750-01-01 00:00:00'
file='$IMOGEN_INSTALL_DIR/rose_stem_imogen/example_temp.nc'
interp='nf'
is_climatology=.false.
!!nfiles=0
nvars=1
!!prescribed_levels=1,2,3,4,5,6,7,8,9,10,11,12,13,14
read_list=.false.
tpl_name=''
var='dtemp_g'
var_name='dtemp_g'
