[namelist:imogen_run_list]
c_emissions=.false.
file_scen_co2_ppmv='$IMOGEN_INSTALL_DIR/rose_stem_imogen/example_co2_conc.dat'
!!file_scen_emits='$IMOGEN_INSTALL_DIR/ancil/emiss_co2.dat'
!!initial_co2_ch4_year=1860
!!land_feed_co2=.true.
!!nyr_emiss=241
!!ocean_feed=.true.
