[namelist:jules_time]
compulsory=true
ns=namelist/Timestepping information
sort-key=03
url=https://metoffice.github.io/jules/latest/namelists/timesteps.nml.html#namelist-JULES_TIME

[namelist:jules_time=l_360]
compulsory=true
description=Use a 360-day year
fail-if=this == '.false.' and namelist:imogen_onoff_switch=l_imogen == '.true.'; # This should be .true. in IMOGEN.
sort-key=1
trigger=namelist:jules_time=l_leap: .false.;
type=logical
url=https://metoffice.github.io/jules/latest/namelists/timesteps.nml.html#JULES_TIME::l_360

[namelist:jules_time=l_leap]
compulsory=true
description=Include leap years
sort-key=2
type=logical
url=https://metoffice.github.io/jules/latest/namelists/timesteps.nml.html#JULES_TIME::l_leap

[namelist:jules_time=l_local_solar_time]
compulsory=true
description=Interpret time in the driving data and throughout the code as local solar time.
sort-key=2
type=logical
url=https://metoffice.github.io/jules/latest/namelists/timesteps.nml.html#JULES_TIME::l_local_solar_time

[namelist:jules_time=main_run_end]
compulsory=true
description=End time for the integration
pattern=\d{4}-\d{2}-\d{2}\s{1}\d{2}:\d{2}:\d{2}
sort-key=5
type=character
url=https://metoffice.github.io/jules/latest/namelists/timesteps.nml.html#JULES_TIME::main_run_end

[namelist:jules_time=main_run_start]
compulsory=true
description=Start time for the integration
pattern=\d{4}-\d{2}-\d{2}\s{1}\d{2}:\d{2}:\d{2}
sort-key=4
type=character
url=https://metoffice.github.io/jules/latest/namelists/timesteps.nml.html#JULES_TIME::main_run_start

[namelist:jules_time=print_step]
description=Number of timesteps between printing timestep information to screen
range=1:
sort-key=6
type=integer
url=https://metoffice.github.io/jules/latest/namelists/timesteps.nml.html#JULES_TIME::print_step

[namelist:jules_time=timestep_len]
compulsory=true
description=Model timestep length (s)
range=1:
sort-key=3
type=integer
url=https://metoffice.github.io/jules/latest/namelists/timesteps.nml.html#JULES_TIME::timestep_len
