[command]
default=run_macro

[file:rose-meta/jules-fcm-make/$VN]
source=$JULES_SOURCE/rose-meta/jules-fcm-make/$VN
mode=symlink

[file:rose-meta/jules-fcm-make/HEAD]
source=$JULES_SOURCE/rose-meta/jules-fcm-make/HEAD
mode=symlink

[file:rose-meta/jules-shared]
source=$JULES_SOURCE/rose-meta/jules-shared
mode=symlink

[file:rose-meta/jules-standalone/$VN]
source=$JULES_SOURCE/rose-meta/jules-standalone/$VN
mode=symlink

[file:rose-meta/jules-standalone/HEAD]
source=$JULES_SOURCE/rose-meta/jules-standalone/HEAD
mode=symlink

[file:rose-stem/app]
source=$JULES_SOURCE/rose-stem/app
mode=symlink
