[command]
ns=Execution command
sort-key=00

[command=default]
description=If serial build was used, this cannot be parallel
sort-key=1
title=Method to use to invoke JULES
value-titles=auto-detect,serial,parallel,profile
values=rose-run jules.exe,jules.exe,rose mpi-launch jules.exe,rose mpi-launch valgrind --tool=callgrind jules.exe
widget[rose-config-edit]=cylc8_compat.ComboBoxValueWidget

[command=rivers-only]
description=UNDER DEVELOPMENT
           =Driving data timestamp issue leads to non-scientific results
sort-key=2
title=Method to use to invoke Standalone Rivers
value-titles=auto-detect
values=rose-run river.exe
widget[rose-config-edit]=cylc8_compat.ComboBoxValueWidget
