[namelist:jules_output]
compulsory=true
ns=namelist/Output
sort-key=11
url=https://metoffice.github.io/jules/latest/namelists/output.nml.html#namelist-JULES_OUTPUT

[namelist:jules_output=dump_period]
compulsory=true
description=Model dumps period
range=1:
sort-key=04
type=integer

[namelist:jules_output=dump_period_unit]
compulsory=true
description=Model dumps period unit, calendar year or second of calendar day
           =If 'Y', dump period in number of calendar years
           =If 'T', dump period in number of seconds into a calendar day
sort-key=05
values='Y','T'

[namelist:jules_output=nprofiles]
compulsory=true
description=Number of output profiles
range=0:
sort-key=03
type=integer
url=https://metoffice.github.io/jules/latest/namelists/output.nml.html#JULES_OUTPUT::nprofiles

[namelist:jules_output=output_dir]
compulsory=true
description=Directory for output files
sort-key=01
type=character
url=https://metoffice.github.io/jules/latest/namelists/output.nml.html#JULES_OUTPUT::output_dir

[namelist:jules_output=run_id]
compulsory=true
description=Identifier for the run
sort-key=02
type=character
url=https://metoffice.github.io/jules/latest/namelists/output.nml.html#JULES_OUTPUT::run_id
