[namelist:jules_initial]
const_val=11*0.0
nvars=11
tpl_name=11*''
use_file=.false.,10*.true.
var='rivers_outflow_rp','tstar_tile','cs','canopy','rgrain',
   ='snow_tile','sthuf','t_soil','rho_snow','snow_depth',
   ='snow_grnd'
var_name=11*''

[namelist:jules_rivers_props]
file='rivers_props_trip_file_list_init_storage.txt'
is_climatology=.false.,.false.,.false.,.true.
nvars=4
use_file=.true.,.true.,.true.,.true.
var='direction','sequence','rivers_outflow_number',
   ='rivers_storage'
var_name='trip_river_routing_direction',
        ='trip_river_routing_sequence','river_number',
        ='river_routing_storage'
