[namelist:jules_inferno]
compulsory=true
description=Options for inferno fire parametrisations
ns=namelist/JULES Science Settings/jules_inferno
sort-key=Section-A12p
title=Fire options
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html

[namelist:jules_inferno=ccdpm_max]
compulsory=true
description=Maximum fraction of DPM consumed by fire
range=0.0:1.0
sort-key=Panel-J06
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::ccdpm_max

[namelist:jules_inferno=ccdpm_min]
compulsory=true
description=Minimum fraction of DPM consumed by fire
range=0.0:1.0
sort-key=Panel-J05
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::ccdpm_min

[namelist:jules_inferno=ccrpm_max]
compulsory=true
description=Maximum fraction of RPM consumed by fire
range=0.0:1.0
sort-key=Panel-J08
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::ccrpm_max

[namelist:jules_inferno=ccrpm_min]
compulsory=true
description=Minimum fraction of RPM consumed by fire
range=0.0:1.0
sort-key=Panel-J07
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::ccrpm_min

[namelist:jules_inferno=flam_fuel_low]
compulsory=true
description=Lower fuel load threshold for flammability
range=0.0:
sort-key=Panel-J12
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::flam_fuel_low

[namelist:jules_inferno=flam_fuel_up]
compulsory=true
description=Upper fuel load threshold for flammability
range=0.0:1.0
sort-key=Panel-J13
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::flam_fuel_up

[namelist:jules_inferno=flam_rain_const]
compulsory=true
description=Rainfall flammability scaling constant
range=0.0:1.0
sort-key=Panel-J14
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::flam_rain_const

[namelist:jules_inferno=flam_rhum_low]
compulsory=true
description=Lower relative humidity threshold for relationship between relative humidity and flammability
range=0.0:100.0
sort-key=Panel-J09
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::flam_rhum_low

[namelist:jules_inferno=flam_rhum_up]
compulsory=true
description=Upper relative humidity threshold for relationship between relative humidity and flammability
range=0.0:100.0
sort-key=Panel-J10
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::flam_rhum_up

[namelist:jules_inferno=flam_sm_func]
compulsory=true
description=Function relating soil moisture to flammability 1=linear, 2=exponential
sort-key=Panel-J11
trigger=namelist:jules_inferno=flam_sm_low: 2;
       =namelist:jules_inferno=flam_sm_up: 2;
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::flam_sm_func
value-titles=(1) linear,
            =(2) exponential
values=1,2

[namelist:jules_inferno=flam_sm_low]
compulsory=true
description=Soil moisture below which flammability is 1.0
range=0.0:1.0
sort-key=Panel-J11b
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::flam_sm_low

[namelist:jules_inferno=flam_sm_up]
compulsory=true
description=Exponential decay parameter for relationship between soil moisture and flammability
range=0.0:10.0
sort-key=Panel-J11c
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::flam_sm_up

[namelist:jules_inferno=z_burn_max]
compulsory=true
description=Maximum burn depth for soil - soil carbon is burned above this level
range=0.0:10.0
sort-key=Panel-J04
type=real
url=https://metoffice.github.io/jules/latest/namelists/jules_inferno.nml.html#JULES_INFERNO::z_burn_max
