[namelist:jules_model_grid]
compulsory=true
ns=namelist/Grid configuration/Model grid
sort-key=14
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#namelist-JULES_MODEL_GRID

[namelist:jules_model_grid=force_1d_grid]
compulsory=true
description=Force 1D model grid
sort-key=2
type=logical
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#JULES_MODEL_GRID::force_1d_grid

[namelist:jules_model_grid=l_bounds]
compulsory=true
description=Subgrid selection method
sort-key=4
trigger=namelist:jules_model_grid=x_bounds: .true.;
       = namelist:jules_model_grid=y_bounds: .true.;
       = namelist:jules_model_grid=npoints: .false.;
       = namelist:jules_model_grid=points_file: .false.;
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#JULES_MODEL_GRID::l_bounds
value-titles=Coordinate bounds,Points list
values=.true.,.false.
widget[rose-config-edit]=cylc8_compat.ComboBoxValueWidget

[namelist:jules_model_grid=land_only]
compulsory=true
description=Model land points only
sort-key=1
type=logical
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#JULES_MODEL_GRID::land_only

[namelist:jules_model_grid=npoints]
compulsory=true
description=Number of points in the points file
range=1:
sort-key=7
type=integer
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#JULES_MODEL_GRID::npoints

[namelist:jules_model_grid=points_file]
compulsory=true
description=Name of the file containing the latitude and longitude of each point
sort-key=8
type=character
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#JULES_MODEL_GRID::points_file

[namelist:jules_model_grid=use_subgrid]
compulsory=true
description=Model only a subgrid of the input grid
sort-key=3
trigger=namelist:jules_model_grid=l_bounds: .true.;
type=logical
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#JULES_MODEL_GRID::use_subgrid

[namelist:jules_model_grid=x_bounds]
compulsory=true
description=Lower and upper bounds (in that order) for x coordinate
fail-if=this(1) > this(2); # Lower bound must be smaller than upper bound
length=2
sort-key=6
type=real
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#JULES_MODEL_GRID::x_bounds

[namelist:jules_model_grid=y_bounds]
compulsory=true
description=Lower and upper bounds (in that order) for y coordinate
fail-if=this(1) > this(2); # Lower bound must be smaller than upper bound
length=2
sort-key=5
type=real
url=https://metoffice.github.io/jules/latest/namelists/model_grid.nml.html#JULES_MODEL_GRID::y_bounds
