[namelist:jules_output]
nprofiles=2

[namelist:jules_output_profile(1)]
output_end='1982-07-03 03:00:00'
output_start='1982-07-01 03:00:00'
var='rflow_rp','frac_fplain_rp'

[namelist:jules_output_profile(2)]
l_land_frac=.true.
output_end='1982-07-03 03:00:00'
output_start='1982-07-01 03:00:00'
profile_name='land'
var='rflow','frac_fplain_lp'

[namelist:jules_overbank]
overbank_model=3
riv_c=0.27
riv_f=0.30

[namelist:jules_rivers]
l_riv_overbank=.true.

[namelist:jules_rivers_props]
const_val=0.0,1.2,0.8
file='$GSWP2_INSTALL_DIR/ancil/qrparm.trip.nc'
is_climatology=.false.,.false.,.false.
nvars=3
read_list=.false.
tpl_name='','',''
use_file=.true.,.false.,.false.
var='direction','logn_mean','logn_stdev'
var_name='trip_river_routing_direction','',''

[namelist:jules_spinup]
max_spinup_cycles=0
!!nvars=1
!!spinup_end='1982-07-07 03:00:00'
!!spinup_start='1982-07-01 03:00:00'
!!terminate_on_spinup_fail=.false.
!!tolerance=-1.0
!!use_percent=.false.
!!var='smcl'

[namelist:jules_time]
main_run_end='1982-07-03 03:00:00'
print_step=24
