[namelist:jules_prnt_control]
ns=namelist/IO System Settings/jules_prnt_control
title=Print Manager Control
url=https://metoffice.github.io/jules/latest/namelists/jules_prnt_control.nml.html#namelist-JULES_PRNT_CONTROL

[namelist:jules_prnt_control=prnt_writers]
compulsory=true
description=Selects which tasks in a parallel job will write informative output.
url=https://metoffice.github.io/jules/latest/namelists/jules_prnt_control.nml.html#JULES_PRNT_CONTROL::jules_prnt_control=prnt_writers
value-titles=All tasks write output,
            =Only the first task (Task 0) writes output
values=1,2
